# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "budpay-custom"
client_id = "d084cc6870c759ebb37dffa9393e38e9"
application_url = "https://obscure-pancake-9q4rg6r59542vpr-4040.app.github.dev"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_gateways,write_payment_sessions"

[auth]
redirect_urls = [
  "https://obscure-pancake-9q4rg6r59542vpr-4040.app.github.dev/auth/callback",
  "https://obscure-pancake-9q4rg6r59542vpr-4040.app.github.dev/auth/shopify/callback",
  "https://obscure-pancake-9q4rg6r59542vpr-4040.app.github.dev/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-2549721b.myshopify.com"
automatically_update_urls_on_dev = true
